<a href="https://colab.research.google.com/github/Yuvahre/deep-learning/blob/main/deep_learning_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/DATA (1).csv')

In [ ]:
df.rename(columns={"1":"Student Age",'2':'Gender','3':'Graduated high-school type','4':'Scholarship type','5':'Additional work','6':'Regular artistic or sports activity','7':'Do you have a partner','8':'Total salary if available','9':'Transportation to the university','10':'Accommodation type in Cyprus','11':'Mothers education','12':'Father education','13':'No. of siblings','14':' Parental status','15':'Mothers occupation','16':'Father occupation','17':'Weekly study hours','18':'Reading frequency(non-scientific books/journals)','19':'Reading frequency (scientific books/journals)','20':'Attendance to the seminars/conferences related to the department','21':'Impact of your projects/activities on your success','22':'Attendance to classes','23':'Preparation to midterm exams 1','24':'Preparation to midterm exams 2','25':'Taking notes in classes','26':'Listening in classes','27':'Discussion improves my interest and success in the course','28':' Flip-classroom','29':'Cumulative grade point average in the last semester (/4.00)','30':'Expected Cumulative grade point average in the graduation (/4.00)'},inplace=True)

In [ ]:
df

STUDENT ID  Student Age  Gender  Graduated high-school type  \
0      STUDENT1            2       2                           3   
1      STUDENT2            2       2                           3   
2      STUDENT3            2       2                           2   
3      STUDENT4            1       1                           1   
4      STUDENT5            2       2                           1   
..          ...          ...     ...                         ...   
140  STUDENT141            2       1                           2   
141  STUDENT142            1       1                           2   
142  STUDENT143            1       1                           1   
143  STUDENT144            2       1                           2   
144  STUDENT145            1       1                           1   

     Scholarship type  Additional work  Regular artistic or sports activity  \
0                   3                1                                    2   
1                   3                1                                    2   
2                   3                2                                    2   
3                   3                1                                    2   
4                   3                2                                    2   
..                ...              ...                                  ...   
140                 3                1                                    1   
141                 4                2                                    2   
142                 4                2                                    2   
143                 4                1                                    1   
144                 5                2                                    2   

     Do you have a partner  Total salary if available  \
0                        2                          1   
1                        2                          1   
2                        2                          2   
3                        1                          2   
4                        1                          3   
..                     ...                        ...   
140                      2                          1   
141                      2                          1   
142                      2                          1   
143                      1                          5   
144                      2                          3   

     Transportation to the university  ...  Preparation to midterm exams 1  \
0                                   1  ...                               1   
1                                   1  ...                               1   
2                                   4  ...                               1   
3                                   1  ...                               1   
4                                   1  ...                               2   
..                                ...  ...                             ...   
140                                 1  ...                               1   
141                                 4  ...                               1   
142                                 1  ...                               1   
143                                 2  ...                               2   
144                                 1  ...                               2   

     Preparation to midterm exams 2  Taking notes in classes  \
0                                 1                        3   
1                                 1                        3   
2                                 1                        2   
3                                 2                        3   
4                                 1                        2   
..                              ...                      ...   
140                               1                        2   
141                               1                        3   
142                               1      

In [ ]:
df.columns

Index(['STUDENT ID', 'Student Age', 'Gender', 'Graduated high-school type',
       'Scholarship type', 'Additional work',
       'Regular artistic or sports activity', 'Do you have a partner',
       'Total salary if available', 'Transportation to the university',
       'Accommodation type in Cyprus', 'Mothers education', 'Father education',
       'No. of siblings', ' Parental status', 'Mothers occupation',
       'Father occupation', 'Weekly study hours',
       'Reading frequency(non-scientific books/journals)',
       'Reading frequency (scientific books/journals)',
       'Attendance to the seminars/conferences related to the department',
       'Impact of your projects/activities on your success',
       'Attendance to classes', 'Preparation to midterm exams 1',
       'Preparation to midterm exams 2', 'Taking notes in classes',
       'Listening in classes',
       'Discussion improves my interest and success in the course',
       ' Flip-classroom',
       'Cumulative grade po

In [ ]:
df.isnull().sum()

STUDENT ID                                                           0
Student Age                                                          0
Gender                                                               0
Graduated high-school type                                           0
Scholarship type                                                     0
Additional work                                                      0
Regular artistic or sports activity                                  0
Do you have a partner                                                0
Total salary if available                                            0
Transportation to the university                                     0
Accommodation type in Cyprus                                         0
Mothers education                                                    0
Father education                                                     0
No. of siblings                                                      0
 Parental status                                                     0
Mothers occupation                                                   0
Father occupation                                                    0
Weekly study hours                                                   0
Reading frequency(non-scientific books/journals)                     0
Reading frequency (scientific books/journals)                        0
Attendance to the seminars/conferences related to the department     0
Impact of your projects/activities on your success                   0
Attendance to classes                                                0
Preparation to midterm exams 1                                       0
Preparation to midterm exams 2                                       0
Taking notes in classes                                              0
Listening in classes                                                 0
Discussion improves my interest and success in the course            0
 Flip-classroom                                                      0
Cumulative grade point average in the last semester (/4.00)          0
Expected Cumulative grade point average in the graduation (/4.00)    0
COURSE ID                                                            0
GRADE                                                                0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.dtypes

STUDENT ID                                                           object
Student Age                                                           int64
Gender                                                                int64
Graduated high-school type                                            int64
Scholarship type                                                      int64
Additional work                                                       int64
Regular artistic or sports activity                                   int64
Do you have a partner                                                 int64
Total salary if available                                             int64
Transportation to the university                                      int64
Accommodation type in Cyprus                                          int64
Mothers education                                                     int64
Father education                                                      int64
No. of siblings                                                       int64
 Parental status                                                      int64
Mothers occupation                                                    int64
Father occupation                                                     int64
Weekly study hours                                                    int64
Reading frequency(non-scientific books/journals)                      int64
Reading frequency (scientific books/journals)                         int64
Attendance to the seminars/conferences related to the department      int64
Impact of your projects/activities on your success                    int64
Attendance to classes                                                 int64
Preparation to midterm exams 1                                        int64
Preparation to midterm exams 2                                        int64
Taking notes in classes                                               int64
Listening in classes                                                  int64
Discussion improves my interest and success in the course             int64
 Flip-classroom                                                       int64
Cumulative grade point average in the last semester (/4.00)           int64
Expected Cumulative grade point average in the graduation (/4.00)     int64
COURSE ID                                                             int64
GRADE                                                                 int64
dtype: object

In [ ]:
!pip install imbalanced-learn

In [ ]:
from imblearn.over_sampling import SMOTE
from collections import Counter

# Assuming 'Grade' is the column representing your grades
X = df.drop(columns=['GRADE','STUDENT ID'], axis=1)  # Features
y = df['GRADE']  # Target

# Display the original class distribution
print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE to generate synthetic samples
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Display the new class distribution
print(f"Resampled class distribution: {Counter(y_resampled)}")

# Combine the resampled data
df_resampled = pd.concat([X_resampled, y_resampled], axis=1)


Original class distribution: Counter({1: 35, 2: 24, 3: 21, 5: 17, 7: 17, 6: 13, 4: 10, 0: 8})
Resampled class distribution: Counter({1: 35, 2: 35, 5: 35, 0: 35, 3: 35, 4: 35, 7: 35, 6: 35})


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
X = df_resampled[['COURSE ID',
    'Cumulative grade point average in the last semester (/4.00)',
    'Mothers education',
    'No. of siblings',
    'Father education',
    'Expected Cumulative grade point average in the graduation (/4.00)',
    'Father occupation',
    'Weekly study hours',
    'Taking notes in classes',
    ' Flip-classroom'
]]
y = df_resampled['GRADE']

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.1, random_state=42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import numpy as np

In [ ]:
num_classes = len(np.unique(y_train))
model2 = Sequential()
model2.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model2.add(Dense(32, activation='relu'))
model2.add(Dropout(0.5))
model2.add(Dense(32, activation='relu'))
model2.add(Dense(num_classes, activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model2.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
history = model2.fit(X_train, y_train, epochs=250, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 8s 221ms/step - accuracy: 0.1092 - loss: 2.1359 - val_accuracy: 0.0784 - val_loss: 2.0991
Epoch 2/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.1135 - loss: 2.1003 - val_accuracy: 0.0980 - val_loss: 2.0873
Epoch 3/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.2053 - loss: 2.0176 - val_accuracy: 0.1176 - val_loss: 2.0773
Epoch 4/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1919 - loss: 2.0210 - val_accuracy: 0.1569 - val_loss: 2.0687
Epoch 5/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.2087 - loss: 2.0326 - val_accuracy: 0.2157 - val_loss: 2.0610
Epoch 6/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2733 - loss: 1.9803 - val_accuracy: 0.2157 - val_loss: 2.0532
Epoch 7/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.2429 - loss: 1.9864 - val_accuracy: 0.2157 - val_loss: 2.0455
Epoch 8/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.2438 - loss: 1.9518 - val_accuracy: 0.1961 - val_loss

In [ ]:
test_loss, test_accuracy = model2.evaluate(X_test, y_test, verbose=1)
print(f"Test Loss: {test_loss}")
print(f"Test Accuracy: {test_accuracy}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7143 - loss: 1.7095
Test Loss: 1.7094881534576416
Test Accuracy: 0.7142857313156128


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Assuming model.predict returns probabilities for each class
y_pred_prob = model2.predict(X_test)

# Convert probabilities to class labels
y_pred = np.argmax(y_pred_prob, axis=1)

# Calculate and print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Calculate and print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
Confusion Matrix:
[[4 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 4 0 0 0]
 [0 0 0 0 0 4 1 0]
 [0 0 0 1 0 0 3 0]
 [1 1 0 0 0 0 0 3]]

Classification Report:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         4
           1       0.00      0.00      0.00         2
           2       0.50      1.00      0.67         2
           3       0.00      0.00      0.00         1
           4       1.00      0.80      0.89         5
           5       1.00      0.80      0.89         5
           6       0.50      0.75      0.60         4
           7       1.00      0.60      0.75         5

    accuracy                           0.71        28
   macro avg       0.60      0.62      0.59        28
weighted avg       0.76      0.71      0.71        28



In [ ]:
from tensorflow.keras.models import save_model

# Save the model to a file
model2.save('/content/dl_assignment_model2.h5')


In [ ]:
pip install streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 62.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 13.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 91.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.9/82.9 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 4.4 MB/s eta 0:00:00
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.0.0
    Uninstalling tenacity-9.0.0:
      Successfully uninstalled tenacity-9.0.0


In [ ]:
import joblib

# Assuming X_train is your training data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)

# Save the fitted scaler
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [ ]:
%%writefile app.py
import streamlit as st
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler
import joblib

# Load the model from Google Drive
model_path = '/content/dl_assignment_model2.h5'  # Update with your model path
model = load_model(model_path, compile=False)  # Avoid recompiling

# Load the fitted scaler
scaler = joblib.load('/content/scaler.pkl')  # Update with your scaler path

# Create a function to preprocess user input
def preprocess_input(data):
    # Use the fitted scaler to transform the input data
    scaled_data = scaler.transform(data)
    return scaled_data

# Streamlit application
def main():
    st.title("Student Performance Prediction")

    # Sidebar for user input
    st.sidebar.header("User Input Features")

    def user_input_features():
        # Collect user inputs for the selected features
        course_id = st.sidebar.number_input('Course ID', min_value=1, max_value=100, value=10)
        gpa_last_sem = st.sidebar.slider('GPA in Last Semester (/4.00)', min_value=0.0, max_value=4.0, value=3.0)
        mothers_education = st.sidebar.selectbox('Mother\'s Education', [0, 1, 2, 3, 4])
        num_siblings = st.sidebar.number_input('Number of Siblings', min_value=0, max_value=10, value=2)
        fathers_education = st.sidebar.selectbox('Father\'s Education', [0, 1, 2, 3, 4])
        expected_gpa_graduation = st.sidebar.slider('Expected GPA at Graduation (/4.00)', min_value=0.0, max_value=4.0, value=3.5)
        fathers_occupation = st.sidebar.selectbox('Father\'s Occupation', [0, 1])
        study_hours = st.sidebar.slider('Weekly Study Hours', min_value=0, max_value=100, value=10)
        taking_notes = st.sidebar.selectbox('Taking Notes in Classes', [0, 1])
        flip_classroom = st.sidebar.selectbox('Flip-Classroom', [0, 1])

        data = {
            'COURSE ID': [course_id],
            'Cumulative grade point average in the last semester (/4.00)': [gpa_last_sem],
            'Mothers education': [mothers_education],
            'No. of siblings': [num_siblings],
            'Father education': [fathers_education],
            'Expected Cumulative grade point average in the graduation (/4.00)': [expected_gpa_graduation],
            'Father occupation': [fathers_occupation],
            'Weekly study hours': [study_hours],
            'Taking notes in classes': [taking_notes],
            ' Flip-classroom': [flip_classroom]
        }
        return pd.DataFrame(data)

    input_features = user_input_features()

    st.subheader("User Input:")
    st.write(input_features)

    # Preprocess the input data
    preprocessed_data = preprocess_input(input_features)

    # Make prediction
    prediction = model.predict(preprocessed_data)
    predicted_class = np.argmax(prediction, axis=1)[0]

    # Map predicted class to label
    class_labels = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6', 'Class 7']  # Update with your class labels
    st.subheader('Prediction')
    st.write(f'Predicted class: {class_labels[predicted_class]}')

if __name__ == "__main__":
    main()


Writing app.py


In [ ]:
!wget -q -O - ipv4.icanhazip.com
! streamlit run app.py & npx localtunnel --port 8501

34.23.222.167



  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.23.222.167:8501

your url is: https://poor-otters-follow.loca.lt
2024-08-26 16:07:49.500554: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-26 16:07:49.530083: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-26 16:07:49.538792: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-26 16:07:51.088122: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/us